# --------------------------------------------------------------------------------------
#
#    ██╗██╗  ██╗   ██╗ █████╗ ███╗   ███╗██╗██████╗  ██████╗ 
#    ██║██║  ╚██╗ ██╔╝██╔══██╗████╗ ████║██║██╔══██╗██╔═══██╗
#    ██║██║   ╚████╔╝ ███████║██╔████╔██║██║██████╔╝██║   ██║
#    ██║██║    ╚██╔╝  ██╔══██║██║╚██╔╝██║██║██╔══██╗██║   ██║
#    ██║███████╗██║   ██║  ██║██║ ╚═╝ ██║██║██║  ██║╚██████╔╝
#    ╚═╝╚══════╝╚═╝   ╚═╝  ╚═╝╚═╝    ╚═╝╚═╝╚═╝  ╚═╝ ╚═════╝ 
#
#    X customization by Xscriptor
#    https://github.com/xscriptor-colors/hyprland/modernizex
#
# --------------------------------------------------------------------------------------

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  ◈ HYPRIDLE CONFIGURATION
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

general {
    lock_cmd = quickshell -p ~/.config/hypr/scripts/quickshell/Lock.qml
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl eval 'hl.dispatch(hl.dsp.dpms({ action = "on" }))'
}

listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

listener {
    timeout = 1200
    on-timeout = systemctl suspend
}
