#!/usr/bin/env bash

# ╔═══════════════════════════════════════════════════════════════════════════╗
# ║ MONITOR AUTO-DETECTION                                                   ║
# ║                                                                           ║
# ║ Detects all connected monitors and generates monitors.conf               ║
# ║ with the highest available refresh rate for each monitor.                ║
# ║                                                                           ║
# ║ Output: ~/.config/hypr/config/monitors.conf                              ║
# ╚═══════════════════════════════════════════════════════════════════════════╝

MONITORS_CONF="$HOME/.config/hypr/config/monitors.conf"
mkdir -p "$(dirname "$MONITORS_CONF")"

# Detect monitors and generate config
hyprctl monitors -j 2>/dev/null | python3 -c "
import json, sys, re

data = sys.stdin.read()
if not data.strip():
    print('# ═══════════════════════════════════════════════════════════════════════')
    print('#  MONITORS (AUTOGENERATED)')
    print('# ═══════════════════════════════════════════════════════════════════════')
    print('monitor = , preferred, auto, 1')
    sys.exit(0)

monitors = json.loads(data)

lines = []
lines.append('# ═══════════════════════════════════════════════════════════════════════')
lines.append('#  MONITORS (AUTOGENERATED BY detect-monitors.sh)')
lines.append('# ═══════════════════════════════════════════════════════════════════════')
lines.append('')

for m in monitors:
    name = m.get('name', 'unknown')
    x = m.get('x', 0)
    y = m.get('y', 0)
    scale = m.get('scale', 1)
    modes = m.get('availableModes', [])

    if not modes:
        lines.append(f'monitor = {name}, preferred, auto, {scale}')
        continue

    best_res = None
    best_rate = 0

    for mode_str in modes:
        match = re.match(r'(\d+x\d+)@?([\d.]+)Hz', mode_str)
        if match:
            res = match.group(1)
            rate = float(match.group(2))
            if rate > best_rate:
                best_rate = rate
                best_res = res

    if best_res:
        rate_int = int(round(best_rate))
        lines.append(f'monitor = {name}, {best_res}@{rate_int}, {x}x{y}, {scale}')
    else:
        lines.append(f'monitor = {name}, preferred, auto, {scale}')

print('\n'.join(lines))
" > "$MONITORS_CONF"

COUNT=$(grep -c '^monitor ' "$MONITORS_CONF" 2>/dev/null || echo 0)
echo "detect-monitors: generated monitors.conf with $COUNT monitor(s)"

# Apply immediately (skip if --silent, used by settings_watcher which does its own reload)
if [[ "$1" != "--silent" ]]; then
    if command -v hyprctl &>/dev/null; then
        hyprctl reload 2>/dev/null || true
    fi
fi
