#!/usr/bin/env bash
# Sync kitty + nvim themes to the active palette (settings.json -> dock.palette).
#
#   - kitty: switches the `include themes/<slug>.conf` line in kitty.conf and
#     syncs `active_border_color` to the palette accent (color1). Kitty reloads
#     kitty.conf automatically on change.
#   - nvim : rewrites lua/config/theme.lua so it reads the active palette slug
#     at startup (falls back to "x"). Safe to re-run at any time.
#
# No Matugen involved. Run from reload.sh and on palette change.

set -e

HOME_DIR="${HOME:-$HOME}"
SETTINGS="$HOME_DIR/.config/hypr/settings.json"
PALETTES="$HOME_DIR/.config/hypr/scripts/quickshell/dock/palettes"

SLUG="$(jq -r '.dock.palette // "x"' "$SETTINGS" 2>/dev/null || echo "x")"
PAL_JSON="$PALETTES/$SLUG.json"
[ -f "$PAL_JSON" ] || PAL_JSON="$PALETTES/x.json"

# ── kitty ──────────────────────────────────────────────────────────────────────────
KITTY_CONF="$HOME_DIR/.config/kitty/kitty.conf"
if [ -f "$KITTY_CONF" ]; then
    if ! grep -qE '^include[[:space:]]+themes/' "$KITTY_CONF"; then
        printf '\ninclude themes/%s.conf\n' "$SLUG" >> "$KITTY_CONF"
    else
        sed -i -E "s|^include[[:space:]]+themes/.*\.conf|include themes/$SLUG.conf|" "$KITTY_CONF"
    fi

    # Palette accent for the active border line (kitty border + cursor).
    ACCENT="$(jq -r '.base16.color1 // "#fc618d"' "$PAL_JSON" 2>/dev/null)"
    [ "${ACCENT:0:1}" = "#" ] || ACCENT="#$ACCENT"
    if grep -qE '^active_border_color' "$KITTY_CONF"; then
        sed -i -E "s|^active_border_color.*|active_border_color $ACCENT|" "$KITTY_CONF"
    else
        printf 'active_border_color %s\n' "$ACCENT" >> "$KITTY_CONF"
    fi
    echo "kitty theme → '$SLUG' (border $ACCENT)"
fi

# ── nvim ───────────────────────────────────────────────────────────────────────────
NVIM_THEME="$HOME_DIR/.config/nvim/lua/config/theme.lua"
if [ -d "$(dirname "$NVIM_THEME")" ]; then
    cat > "$NVIM_THEME" <<LUAEOF
-- Auto-generated by theme-sync.sh — follows the active palette (dock/palettes).
-- Re-generate with: bash ~/.config/hypr/scripts/theme-sync.sh
local function current_palette()
  local home = vim.fn.expand("~")
  local f = io.popen('jq -r ".dock.palette // \\"x\\"" ' .. vim.fn.shellescape(home .. "/.config/hypr/settings.json") .. " 2>/dev/null")
  if not f then return "x" end
  local slug = f:read("*l")
  f:close()
  return (slug ~= "" and slug) or "x"
end
vim.g.theme = vim.g.theme or current_palette()
require("themes").apply(vim.g.theme)
LUAEOF
    echo "nvim theme.lua → reads active palette ($SLUG)"
fi
