# ═══════════════════════════════════════════════════════════════════════════
# nvim — palettes.lua + active-theme bootstrap.
#
# The nvim config (plugins, keymaps, options) comes from the user's own repo
# (cloned to ~/.config/nvim). Only the PALETTE DATA (lua/themes/palettes.lua)
# and the theme bootstrap (lua/config/theme.lua) are regenerated here; nothing
# else is touched.
# ═══════════════════════════════════════════════════════════════════════════
from __future__ import annotations

from ..core import palette_bg_fg

NAME = "nvim"
DESCRIPTION = "palettes.lua + active-theme bootstrap"

NVIM_REL = ".config/nvim"


def available(env) -> bool:
    nvim = env.home / NVIM_REL
    return (nvim / "lua/themes").is_dir() and (nvim / "lua/config").is_dir()


def apply(env) -> list:
    nvim = env.home / NVIM_REL

    # ── 1) Data for every palette ──
    entries = []
    for pal in env.palettes:
        slug = pal.get("slug") or "?"
        b = pal.get("base16") or {}
        bg, fg = palette_bg_fg(pal)
        lines = ["  %s = {" % slug]
        for i in range(16):
            lines.append('    color%d = "%s",' % (i, b.get("color%d" % i, "#000000")))
        lines.append('    background = "%s",' % bg)
        lines.append('    foreground = "%s",' % fg)
        lines.append("  },")
        entries.append("\n".join(lines))

    palettes_lua = "local M = {\n" + "\n".join(entries) + "\n}\n\n"
    palettes_lua += '''function M.strip_alpha(hex)
  if #hex == 9 then
    return hex:sub(1, 7)
  end
  return hex
end

return M
'''
    env.write(nvim / "lua/themes/palettes.lua", palettes_lua)

    # ── 2) Bootstrap: read the active palette from settings.json and apply it ──
    theme_lua = '''-- Auto-generated by theme-sync.sh — follows the active palette (dock/palettes).
-- The rest of the nvim config comes from the user's own repo.
local function current_palette()
  local home = vim.fn.expand("~")
  local f = io.popen('jq -r ".dock.palette // \\\\"x\\\\"" ' .. vim.fn.shellescape(home .. "/.config/hypr/settings.json") .. " 2>/dev/null")
  if not f then return "x" end
  local slug = f:read("*l")
  f:close()
  return (slug ~= "" and slug) or "x"
end
vim.g.theme = vim.g.theme or current_palette()
require("themes").apply(vim.g.theme)
'''
    env.write(nvim / "lua/config/theme.lua", theme_lua)

    return ["nvim palettes regenerated from dock/palettes: %d → active '%s'"
            % (len(entries), env.slug)]
