# ═══════════════════════════════════════════════════════════════════════════
# opencode — per-palette themes + active theme in tui.json.
#
# Generates ~/.config/opencode/themes/<slug>.json (base16 defs + structural
# colors derived from background/foreground) and sets the active palette's
# theme in tui.json (atomic, keeps the rest of the keys). Custom themes whose
# slug is not a palette are kept; one-time snapshot of pre-existing themes in
# themes.bak. The TUI may need a restart to re-read it.
# ═══════════════════════════════════════════════════════════════════════════
from __future__ import annotations

import json

from ..core import load_json, mix, palette_bg_fg

NAME = "opencode"
DESCRIPTION = "per-palette themes + active theme in tui.json"

OC_REL = ".config/opencode"
# Manifest of slugs generated by us (the dir may hold user themes; only what we
# generated and is no longer a palette gets removed).
STATE_REL = ".local/state/quickshell/themesync/opencode-themes.json"


def available(env) -> bool:
    return (env.home / OC_REL / "themes").is_dir()


def apply(env) -> list:
    out = []
    root = env.home / OC_REL
    themes = root / "themes"
    env.copytree_once(themes, root / "themes.bak")

    # ── 1) Regenerate per-palette themes ──
    slugs = []
    for pal in env.palettes:
        slug = pal.get("slug") or "?"
        b = pal.get("base16") or {}
        bg, fg = palette_bg_fg(pal)

        def c(i, fallback=fg):
            return b.get("color%d" % i) or fallback

        defs = {
            "bg0": bg,
            "red": c(1), "green": c(2), "yellow": c(3), "orange": c(4),
            "purple": c(5), "cyan": c(6), "fg0": fg, "muted": c(8),
            "redBright": c(9, c(1)), "greenBright": c(10, c(2)),
            "yellowBright": c(11, c(3)), "orangeBright": c(12, c(4)),
            "purpleBright": c(13, c(5)), "cyanBright": c(14, c(6)),
            "fgBright": c(15, fg),
        }
        theme = {
            "primary": "cyan", "secondary": "purple", "accent": "cyan",
            "error": "red", "warning": "yellow", "success": "green", "info": "cyan",
            "text": "fg0", "textMuted": "muted", "background": "bg0",
            "backgroundPanel": mix(bg, fg, 0.06),
            "backgroundElement": mix(bg, fg, 0.12),
            "border": mix(bg, fg, 0.20),
            "borderActive": "cyan",
            "borderSubtle": mix(bg, fg, 0.10),
            "diffAdded": "green", "diffRemoved": "red", "diffContext": "fg0",
            "diffHunkHeader": "muted", "diffHighlightAdded": "green",
            "diffHighlightRemoved": "red",
            "diffAddedBg": mix(bg, c(2), 0.15),
            "diffRemovedBg": mix(bg, c(1), 0.15),
            "diffContextBg": "bg0", "diffLineNumber": "muted",
            "diffAddedLineNumberBg": mix(bg, c(2), 0.15),
            "diffRemovedLineNumberBg": mix(bg, c(1), 0.15),
            "markdownText": "fg0", "markdownHeading": "cyan", "markdownLink": "orange",
            "markdownLinkText": "cyan", "markdownCode": "green",
            "markdownBlockQuote": "muted", "markdownEmph": "yellow",
            "markdownStrong": "yellow", "markdownHorizontalRule": "muted",
            "markdownListItem": "cyan", "markdownListEnumeration": "cyan",
            "markdownImage": "orange", "markdownImageText": "cyan",
            "markdownCodeBlock": "fg0",
            "syntaxComment": "muted", "syntaxKeyword": "purple", "syntaxFunction": "cyan",
            "syntaxVariable": "orange", "syntaxString": "green", "syntaxNumber": "yellow",
            "syntaxType": "orange", "syntaxOperator": "red", "syntaxPunctuation": "fg0",
        }
        data = {"$schema": "https://opencode.ai/theme.json", "defs": defs, "theme": theme}
        env.write(themes / (slug + ".json"), json.dumps(data, indent=2) + "\n")
        slugs.append(slug)

    # ── 2) Orphan cleanup: only what we generated ──
    # The opencode themes directory may hold user themes, so (unlike
    # kitty/starship/Qt, whose directories are 100% ours) a manifest of the
    # generated slugs is kept and only slugs that are no longer a palette get
    # removed. Without a previous manifest nothing is deleted.
    state = env.home / STATE_REL
    previous = load_json(state, []) or []
    for slug in previous:
        if slug not in slugs:
            env.unlink(themes / (slug + ".json"))
    env.write(state, json.dumps(slugs, indent=2) + "\n")

    out.append("opencode themes regenerated from dock/palettes: %d" % len(slugs))

    # ── 3) Active theme in tui.json (keeps the rest) ──
    tui = root / "tui.json"
    if tui.is_file():
        data = load_json(tui)
        if isinstance(data, dict):
            data["theme"] = env.slug
            env.write(tui, json.dumps(data, indent=2, ensure_ascii=False) + "\n")
            out.append("opencode theme → '%s'" % env.slug)
    return out
