# ═══════════════════════════════════════════════════════════════════════════
# rofi — colors.rasi + config.rasi.
#
# colors.rasi is imported by launcher.rasi (emoji picker SUPER+., drun,
# scale-menu) and selector.rasi; it is regenerated from the active palette.
# config.rasi (colors only, imports colors.rasi) is also generated so bare
# `rofi -dmenu` calls without -theme (gpu-mode.sh, monitor-manager.sh) follow
# the palette without changing their layout. Only these two files are written.
# ═══════════════════════════════════════════════════════════════════════════
from __future__ import annotations

from ..core import mix, palette_bg_fg, palette_hex

NAME = "rofi"
DESCRIPTION = "colors.rasi + config.rasi (dmenu included)"

ROFI_REL = ".config/rofi"


def available(env) -> bool:
    return (env.home / ROFI_REL).is_dir()


def apply(env) -> list:
    rdir = env.home / ROFI_REL
    pal = env.palette
    bg, fg = palette_bg_fg(pal)
    c5 = palette_hex(pal, "color5", fg)

    colors = "\n".join([
        "/* Auto-generated by theme-sync.sh (xscriptor-colors) — palette '%s'. Do not edit. */" % env.slug,
        "* {",
        "    background:     %sCC;" % mix(bg, fg, 0.05),
        "    background-alt: %sFF;" % mix(bg, fg, 0.10),
        "    foreground:     %s;" % fg,
        "    selected:       %s;" % c5,
        "    active:         %s;" % palette_hex(pal, "color2", fg),
        "    urgent:         %s;" % palette_hex(pal, "color1", fg),
        "    border-col:     %s;" % c5,
        "    border-col-2:   %s;" % palette_hex(pal, "color13", c5),
        "}",
    ]) + "\n"
    env.write(rdir / "colors.rasi", colors)

    config = "\n".join([
        "/* Auto-generated by theme-sync.sh (xscriptor-colors) — palette '%s'. Do not edit. */" % env.slug,
        '@import "colors.rasi"',
        "",
        "* {",
        "    background-color: transparent;",
        "    text-color: @foreground;",
        "}",
        "",
        "window {",
        "    background-color: @background;",
        "    border-color: @border-col;",
        "}",
        "",
        "inputbar, entry, prompt, textbox {",
        "    background-color: @background-alt;",
        "    text-color: @foreground;",
        "}",
        "",
        "element selected.normal {",
        "    background-color: @background-alt;",
        "    text-color: @foreground;",
        "    border-color: @border-col;",
        "}",
    ]) + "\n"
    env.write(rdir / "config.rasi", config)

    return ["rofi colors → '%s' (colors.rasi + config.rasi)" % env.slug]
