# ═══════════════════════════════════════════════════════════════════════════
# starship — per-palette themes + fixed config and export in .zshrc/.bashrc.
#
# The structural template is ~/.config/xscriptor/starship/starship.toml
# (canonical, NEVER rewritten): its canonical hex values are mapped to palette
# roles. themes/x.toml is a generated OUTPUT, not a template (using it as a
# template corrupted itself destructively).
#
# Since starship re-reads its config on every prompt, a fixed file
# ~/.config/starship.toml (with a marker) is written so a palette change
# applies on the next prompt of EVERY open shell. If the user has their own
# config without the marker, it is NOT touched and the switch is kept through
# STARSHIP_CONFIG pointing at the per-slug theme.
# ═══════════════════════════════════════════════════════════════════════════
from __future__ import annotations

from ..core import read_text

NAME = "starship"
DESCRIPTION = "per-palette themes + fixed config and export in .zshrc/.bashrc"

# Marker of the fixed file (identifies ours; if missing, it is user config).
MARKER = "# Auto-generated by theme-sync.sh (xscriptor-colors). Do not edit."

# Canonical template hex → palette role. The template's structural darks
# (#2a2a2a/#141414/#0b0b0b) are fixed by design; only accents and foreground
# are palette-driven.
ROLES = {
    "#363537": "color0", "#fc618d": "color1", "#7bd88f": "color2",
    "#fce566": "color3", "#948ae3": "color5", "#5ad4e6": "color6",
    "#f7f1ff": "color7", "#69676c": "color8",
}

THEMES_REL = ".config/xscriptor/starship/themes"
TEMPLATE_REL = ".config/xscriptor/starship/starship.toml"
ACTIVE_REL = ".config/starship.toml"
FIXED_PATH = ".config/starship.toml"


def available(env) -> bool:
    return (env.home / THEMES_REL).is_dir() and (env.home / TEMPLATE_REL).is_file()


def apply(env) -> list:
    out = []
    themes = env.home / THEMES_REL
    template = read_text(env.home / TEMPLATE_REL)
    if not template.strip():
        # Empty/corrupt template: warn and skip (the rest keeps running).
        return ["WARN: starship template is empty, skipping starship themes: %s"
                % (env.home / TEMPLATE_REL)]

    # ── 1) Regenerate per-palette themes from the template ──
    slugs = []
    for pal in env.palettes:
        slug = pal.get("slug") or "?"
        b = pal.get("base16") or {}
        text = template
        for hexv, role in ROLES.items():
            text = text.replace(hexv, b.get(role, hexv))
        env.write(themes / (slug + ".toml"), text)
        slugs.append(slug)

    for stale in themes.glob("*.toml"):
        if stale.stem not in slugs:
            env.unlink(stale)
    out.append("starship themes regenerated from dock/palettes: %d" % len(slugs))

    # ── 2) Fixed active file (~/.config/starship.toml) ──
    active = env.home / ACTIVE_REL
    active_theme = themes / (env.slug + ".toml")
    fixed_ok = False
    if active.is_file() and MARKER not in read_text(active):
        out.append("starship: ~/.config/starship.toml is user config; "
                   "keeping it (STARSHIP_CONFIG per slug)")
    else:
        env.write(active, MARKER + "\n" + read_text(active_theme))
        fixed_ok = True
        out.append("starship active config → '%s' (~/.config/starship.toml)" % env.slug)

    # ── 3) STARSHIP_CONFIG in .zshrc/.bashrc ──
    # Only our own export is rewritten (per-slug themes or the fixed path);
    # a custom export is never clobbered. Fish uses the default path (fixed
    # file), so it is intentionally left untouched.
    target = active if fixed_ok else active_theme
    for rc in (env.home / ".zshrc", env.home / ".bashrc"):
        if not rc.is_file():
            continue
        out.extend(_update_rc(env, rc, target, fixed_ok))
    return out


def _export_value(line: str) -> str:
    """Value of `export STARSHIP_CONFIG=...` (equivalent to the old sed)."""
    rest = line.partition("=")[2].strip()
    if rest.startswith('"'):
        end = rest.find('"', 1)
        return rest[1:end] if end != -1 else rest[1:]
    return rest


def _update_rc(env, rc, target, fixed_ok: bool) -> list:
    out = []
    name = rc.name
    text = read_text(rc)
    lines = text.splitlines()
    idx = next((i for i, l in enumerate(lines) if l.startswith("export STARSHIP_CONFIG=")), None)

    if idx is not None:
        cur = _export_value(lines[idx])
        if "/xscriptor/starship/themes/" in cur:
            lines[idx] = 'export STARSHIP_CONFIG="%s"' % target
            env.write(rc, "\n".join(lines) + "\n")
            out.append("starship (%s) → '%s'" % (name, target))
        elif cur == str(env.home / FIXED_PATH):
            if fixed_ok:
                out.append("starship (%s) → default ~/.config/starship.toml" % name)
            else:
                out.append("starship: STARSHIP_CONFIG in %s points to your own config; "
                           "left untouched" % name)
        else:
            out.append("starship: custom STARSHIP_CONFIG detected in %s; left untouched (%s)"
                       % (name, cur))
    elif not fixed_ok:
        env.write(rc, text + 'export STARSHIP_CONFIG="%s"\n' % target)
        out.append("starship (%s) → '%s' (export added)" % (name, target))
    return out
