# ═══════════════════════════════════════════════════════════════════════════
# starship — temas por paleta + config fija y export en .zshrc/.bashrc.
#
# La plantilla estructural es ~/.config/xscriptor/starship/starship.toml
# (canónica, NUNCA se reescribe): sus hex canónicos se mapean a roles de la
# paleta. themes/x.toml es un OUTPUT generado, no un template (usarlo como
# template corrompía de forma auto-destructiva).
#
# Como starship relee su config en cada prompt, se escribe un archivo fijo
# ~/.config/starship.toml (con marcador) para que el cambio de paleta se
# aplique en la siguiente línea de TODAS las shells abiertas. Si el usuario
# tiene su propia config sin marcador, NO se toca y se mantiene el cambio por
# STARSHIP_CONFIG apuntando al tema por slug.
# ═══════════════════════════════════════════════════════════════════════════
from __future__ import annotations

from ..core import read_text

NAME = "starship"
DESCRIPTION = "temas por paleta + config fija y export en .zshrc/.bashrc"

# Marcador del archivo fijo (nos identifica; si falta, es config del usuario).
MARKER = "# Auto-generated by theme-sync.sh (xscriptor-colors). Do not edit."

# Hex canónicos del template → rol de paleta. Los darks estructurales del
# template (#2a2a2a/#141414/#0b0b0b) son fijos por diseño; solo se palettizan
# acentos y foreground.
ROLES = {
    "#363537": "color0", "#fc618d": "color1", "#7bd88f": "color2",
    "#fce566": "color3", "#948ae3": "color5", "#5ad4e6": "color6",
    "#f7f1ff": "color7", "#69676c": "color8",
}

THEMES_REL = ".config/xscriptor/starship/themes"
TEMPLATE_REL = ".config/xscriptor/starship/starship.toml"
ACTIVE_REL = ".config/starship.toml"
FIXED_PATH = ".config/starship.toml"


def available(env) -> bool:
    return (env.home / THEMES_REL).is_dir() and (env.home / TEMPLATE_REL).is_file()


def apply(env) -> list:
    out = []
    themes = env.home / THEMES_REL
    template = read_text(env.home / TEMPLATE_REL)
    if not template.strip():
        # Plantilla vacía/corrupta: avisar y saltar (el resto sigue).
        return ["WARN: starship template is empty, skipping starship themes: %s"
                % (env.home / TEMPLATE_REL)]

    # ── 1) Regenerar temas por paleta desde la plantilla ──
    slugs = []
    for pal in env.palettes:
        slug = pal.get("slug") or "?"
        b = pal.get("base16") or {}
        text = template
        for hexv, role in ROLES.items():
            text = text.replace(hexv, b.get(role, hexv))
        env.write(themes / (slug + ".toml"), text)
        slugs.append(slug)

    for stale in themes.glob("*.toml"):
        if stale.stem not in slugs:
            env.unlink(stale)
    out.append("starship themes regenerated from dock/palettes: %d" % len(slugs))

    # ── 2) Archivo fijo activo (~/.config/starship.toml) ──
    active = env.home / ACTIVE_REL
    active_theme = themes / (env.slug + ".toml")
    fixed_ok = False
    if active.is_file() and MARKER not in read_text(active):
        out.append("starship: ~/.config/starship.toml es config propia; "
                   "se conserva (STARSHIP_CONFIG por slug)")
    else:
        env.write(active, MARKER + "\n" + read_text(active_theme))
        fixed_ok = True
        out.append("starship active config → '%s' (~/.config/starship.toml)" % env.slug)

    # ── 3) STARSHIP_CONFIG en .zshrc/.bashrc ──
    # Solo se reescribe el export nuestro (temas por slug o el path fijo);
    # nunca se pisa un export custom. Fish usa el path por defecto (archivo
    # fijo), así que se deja intacto.
    target = active if fixed_ok else active_theme
    for rc in (env.home / ".zshrc", env.home / ".bashrc"):
        if not rc.is_file():
            continue
        out.extend(_update_rc(env, rc, target, fixed_ok))
    return out


def _export_value(line: str) -> str:
    """Valor de `export STARSHIP_CONFIG=...` (equivale al sed del script viejo)."""
    rest = line.partition("=")[2].strip()
    if rest.startswith('"'):
        end = rest.find('"', 1)
        return rest[1:end] if end != -1 else rest[1:]
    return rest


def _update_rc(env, rc, target, fixed_ok: bool) -> list:
    out = []
    name = rc.name
    text = read_text(rc)
    lines = text.splitlines()
    idx = next((i for i, l in enumerate(lines) if l.startswith("export STARSHIP_CONFIG=")), None)

    if idx is not None:
        cur = _export_value(lines[idx])
        if "/xscriptor/starship/themes/" in cur:
            lines[idx] = 'export STARSHIP_CONFIG="%s"' % target
            env.write(rc, "\n".join(lines) + "\n")
            out.append("starship (%s) → '%s'" % (name, target))
        elif cur == str(env.home / FIXED_PATH):
            if fixed_ok:
                out.append("starship (%s) → default ~/.config/starship.toml" % name)
            else:
                out.append("starship: STARSHIP_CONFIG en %s apunta a tu config propia; "
                           "no se toca" % name)
        else:
            out.append("starship: STARSHIP_CONFIG custom detectado en %s; no se toca (%s)"
                       % (name, cur))
    elif not fixed_ok:
        env.write(rc, text + 'export STARSHIP_CONFIG="%s"\n' % target)
        out.append("starship (%s) → '%s' (export añadido)" % (name, target))
    return out
