# ═══════════════════════════════════════════════════════════════════════════
# xfetch — per-palette themes + active theme in config.jsonc.
#
# Generates one xfetch theme per palette in ~/.config/xfetch/themes/<slug>.jsonc
# following the official theme structure (per-module colors + logo_color) and
# activates the active palette's theme in config.jsonc (textual edit: keeps
# comments and avoids the duplicate key that `xfetch theme set` produces).
#
# The module mapping is the canonical one from the registry (helsinki) resolved
# to the palette's EXACT HEX: xfetch >= 1.0.0 accepts #rrggbb in colors
# (truecolor, no terminal dependency); older versions fall back to the ANSI
# names, which kitty resolved. logo_color carries the exact accent.
#
# Only themes generated by us (first-line marker) whose slug is no longer a
# palette are removed; user-owned themes stay untouched.
# ═══════════════════════════════════════════════════════════════════════════
from __future__ import annotations

import json
import re

from ..core import palette_hex, read_text

NAME = "xfetch"
DESCRIPTION = "per-palette themes (hex) + active theme in config.jsonc"

XFETCH_REL = ".config/xfetch"
MARKER = "// Generated by xscriptor-colors theme-sync"

# Module → canonical ANSI color (from the official registry's helsinki theme).
MODULES = {
    "os": "Green", "kernel": "Blue", "hostname": "Magenta", "uptime": "Red",
    "packages": "Green", "shell": "Green", "terminal": "Cyan", "wm": "Blue",
    "cpu": "Red", "gpu": "Magenta", "memory": "Yellow", "swap": "Red",
    "disk": "Cyan", "battery": "Green", "user": "Magenta", "datetime": "Cyan",
    "local_ip": "Blue", "palette": "Green",
    "plugin:docker": "Cyan", "plugin:github-stats": "Blue",
    "plugin:music-player": "Yellow", "plugin:weather": "Cyan",
    "plugin:timezone": "Blue", "plugin:user-info": "Magenta",
    "plugin:display-resolution": "Green", "plugin:theme-detection": "Blue",
}
ANSI_INDEX = {"Black": 0, "Red": 1, "Green": 2, "Yellow": 3, "Blue": 4,
              "Magenta": 5, "Cyan": 6, "White": 7, "Grey": 8}


def available(env) -> bool:
    return (env.home / XFETCH_REL).is_dir()


def _hex_support(env) -> bool:
    """Does the installed xfetch accept hex in colors? (>= 1.0.0)."""
    binary = env.binary("xfetch")
    if not binary:
        return False
    m = re.search(r"\d+", env.capture([binary, "--version"]))
    return bool(m) and int(m.group(0)) >= 1


def apply(env) -> list:
    out = []
    root = env.home / XFETCH_REL
    themes = root / "themes"
    env.mkdir(themes)
    use_hex = _hex_support(env)

    # ── 1) One theme per palette ──
    slugs = []
    for pal in env.palettes:
        slug = pal.get("slug") or "?"
        b = pal.get("base16") or {}
        fg = pal.get("foreground") or b.get("color7") or "#ffffff"

        def c(i, fallback=fg):
            return b.get("color%d" % i) or fallback

        if use_hex:
            colors = {mod: c(ANSI_INDEX[name]) for mod, name in MODULES.items()}
        else:
            colors = {mod: name for mod, name in MODULES.items()}
        body = json.dumps({"colors": colors, "logo_color": c(5)}, indent=4)
        env.write(themes / (slug + ".jsonc"),
                  MARKER + " — palette '" + slug + "'. Do not edit.\n" + body + "\n")
        slugs.append(slug)

    # ── 2) Cleanup of our orphans ──
    for f in themes.glob("*.jsonc"):
        if f.stem in slugs:
            continue
        first = read_text(f).splitlines()
        if first and first[0].startswith(MARKER):
            env.unlink(f)

    # ── 3) Active theme in config.jsonc ──
    # Textual: replace EVERY "theme" occurrence so previous duplicates left by
    # `xfetch theme set` cannot win at the end.
    cfg = root / "config.jsonc"
    if (themes / (env.slug + ".jsonc")).is_file():
        if cfg.is_file():
            txt = read_text(cfg)
            pat = re.compile(r'("theme"\s*:\s*)"[^"]*"')
            if pat.search(txt):
                txt = pat.sub(lambda m: m.group(1) + '"' + env.slug + '"', txt)
            else:
                txt = re.sub(r"\{", '{\n    "theme": "' + env.slug + '",', txt, count=1)
            env.write(cfg, txt)
            out.append("xfetch theme → '%s' (config.jsonc)" % env.slug)
        else:
            env.write(cfg, '{\n    "theme": "%s"\n}\n' % env.slug)
            out.append("xfetch theme → '%s' (config.jsonc created)" % env.slug)

    out.append("xfetch themes regenerated from dock/palettes: %d" % len(slugs))
    return out
