# ═══════════════════════════════════════════════════════════════════════════
# xtop — per-palette themes + active theme.
#
# Generates ~/.config/xtop/themes/<slug>.jsonc for every palette and activates
# the current one with `xtop --ct <slug>` (persists; live instances follow on
# the next tick). Custom themes whose slug is not a palette are kept; only
# themes generated by us (header "synced from dock/palettes/") are removed when
# orphaned. One-time snapshot of pre-existing themes in themes.bak.
# ═══════════════════════════════════════════════════════════════════════════
from __future__ import annotations

import json

from ..core import palette_bg_fg, read_text

NAME = "xtop"
DESCRIPTION = "per-palette themes + active theme (xtop --ct)"

THEMES_REL = ".config/xtop/themes"
HEADER_MARK = "synced from dock/palettes/"


def available(env) -> bool:
    return (env.home / THEMES_REL).is_dir()


def apply(env) -> list:
    out = []
    themes = env.home / THEMES_REL
    env.copytree_once(themes, str(themes) + ".bak")

    # ── 1) Regenerate per-palette themes ──
    slugs = []
    for pal in env.palettes:
        slug = pal.get("slug") or "?"
        b = pal.get("base16") or {}
        bg, fg = palette_bg_fg(pal)
        palette = [b.get("color%d" % i, bg) for i in range(16)]
        body = json.dumps({
            "name": slug,
            "background": bg,
            "foreground": fg,
            "palette": palette,
        }, indent=4)
        header = "// %s -- synced from dock/palettes/%s.json by theme-sync.sh\n" % (
            pal.get("name", slug), slug)
        env.write(themes / (slug + ".jsonc"), header + body + "\n")
        slugs.append(slug)

    # ── 2) Cleanup of our orphans ──
    for stale in themes.glob("*.jsonc"):
        if stale.stem in slugs:
            continue
        first = read_text(stale).splitlines()
        if first and HEADER_MARK in first[0]:
            env.unlink(stale)
    out.append("xtop themes regenerated from dock/palettes: %d" % len(slugs))

    # ── 3) Activate the current palette's theme ──
    binary = env.binary("xtop")
    if binary and (themes / (env.slug + ".jsonc")).is_file():
        if env.dry_run:
            env.note("[dry-run] xtop --ct %s" % env.slug)
        elif env.run([binary, "--ct", env.slug], timeout=10):
            out.append("xtop theme → '%s'" % env.slug)
    return out
