#!/usr/bin/env bash
# Persist window effect settings across Hyprland reloads
# Usage: persist.sh <active_opacity> <inactive_opacity> <rounding> <blur_size> <blur_passes> [gaps_in] [gaps_out] [border_size]
#
# Writes Lua override modules loaded at the end of hyprland.lua so the
# Window Controls widget keeps its effects after a reload/restart.

ACTIVE="$1"
INACTIVE="$2"
ROUNDING="$3"
BLUR_SIZE="$4"
BLUR_PASSES="$5"
GAPS_IN="${6:-16}"
GAPS_OUT="${7:-25}"
BORDER_SIZE="${8:-2}"
SHADOW_RANGE="${9:-35}"
SHADOW_RENDER_POWER="${10:-5}"
SHADOW_OFFSET_X="${11:-0}"
SHADOW_OFFSET_Y="${12:-10}"

CONF_DIR="$HOME/.config/hypr/config"
mkdir -p "$CONF_DIR"

cat > "$CONF_DIR/window-effects.lua" << LUA
-- Auto-generated by Window Controls widget
hl.config({
    decoration = {
        active_opacity   = $ACTIVE,
        inactive_opacity = $INACTIVE,
        rounding         = $ROUNDING,

        blur = {
            size   = $BLUR_SIZE,
            passes = $BLUR_PASSES,
        },

        shadow = {
            range        = $SHADOW_RANGE,
            render_power = $SHADOW_RENDER_POWER,
            offset       = { $SHADOW_OFFSET_X, $SHADOW_OFFSET_Y },
        },
    },
})
LUA

# Write gap/border to a separate file
cat > "$CONF_DIR/gaps.lua" << LUA
-- Auto-generated by Window Controls widget
hl.config({
    general = {
        gaps_in     = $GAPS_IN,
        gaps_out    = $GAPS_OUT,
        border_size = $BORDER_SIZE,
    },
})
LUA

echo "window-effects.lua + gaps.lua saved"

# Reload so Hyprland picks up the overrides
hyprctl reload >/dev/null 2>&1 || true
