#!/usr/bin/env bash
# Persist window effect settings across Hyprland reloads
# Usage: persist.sh <active_opacity> <inactive_opacity> <rounding> <blur_size> <blur_passes>

ACTIVE="$1"
INACTIVE="$2"
ROUNDING="$3"
BLUR_SIZE="$4"
BLUR_PASSES="$5"

CONF_DIR="$HOME/.config/hypr/config"
mkdir -p "$CONF_DIR"

cat > "$CONF_DIR/window-effects.conf" << CONF
# Auto-generated by Window Controls widget
decoration {
    active_opacity = $ACTIVE
    inactive_opacity = $INACTIVE
    rounding = $ROUNDING
    blur {
        size = $BLUR_SIZE
        passes = $BLUR_PASSES
    }
}
CONF

echo "window-effects.conf saved"
