#!/usr/bin/env bash
# Persist window effect settings across Hyprland reloads
# Usage: persist.sh <active_opacity> <inactive_opacity> <rounding> <blur_size> <blur_passes> [gaps_in] [gaps_out] [border_size]

ACTIVE="$1"
INACTIVE="$2"
ROUNDING="$3"
BLUR_SIZE="$4"
BLUR_PASSES="$5"
GAPS_IN="${6:-16}"
GAPS_OUT="${7:-25}"
BORDER_SIZE="${8:-2}"
SHADOW_RANGE="${9:-35}"
SHADOW_RENDER_POWER="${10:-5}"
SHADOW_OFFSET_X="${11:-0}"
SHADOW_OFFSET_Y="${12:-10}"

CONF_DIR="$HOME/.config/hypr/config"
mkdir -p "$CONF_DIR"

cat > "$CONF_DIR/window-effects.conf" << CONF
# Auto-generated by Window Controls widget
decoration {
    active_opacity = $ACTIVE
    inactive_opacity = $INACTIVE
    rounding = $ROUNDING
    blur {
        size = $BLUR_SIZE
        passes = $BLUR_PASSES
    }
    shadow {
        range = $SHADOW_RANGE
        render_power = $SHADOW_RENDER_POWER
        offset = $SHADOW_OFFSET_X $SHADOW_OFFSET_Y
    }
}
CONF

# Write gap/border to a separate file (never overwritten by settings_watcher)
cat > "$CONF_DIR/gaps.conf" << CONF
# Auto-generated by Window Controls widget
general {
    gaps_in = $GAPS_IN
    gaps_out = $GAPS_OUT
    border_size = $BORDER_SIZE
}
CONF

echo "window-effects.conf saved"
