#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════
# persist-hypr.sh — Overrides de Hyprland generados por el panel Settings.
#
# Mismo patrón que window-controls/persist.sh: escribe módulos Lua en
# ~/.config/hypr/config/ (cargados al final de hyprland.lua → siempre ganan)
# y recarga Hyprland. Escritura atómica (tmp + mv en el mismo dir) y
# validación con `luac -p`: si el Lua generado no compila, se descarta el
# fichero y se sale con error (nunca se deja un override roto en config/).
#
# Uso:
#   persist-hypr.sh animations <enabled 0|1> <speed_multiplier>
#   persist-hypr.sh input <sensitivity> <accel_profile> <tap 0|1> <natural 0|1> <dwt 0|1>
#
# Entorno:
#   HYPR_CONFIG_DIR  directorio de salida (default ~/.config/hypr/config);
#                    los tests lo apuntan a un dir temporal.
#   HYPR_NO_RELOAD=1 no ejecuta `hyprctl reload` (tests).
#
# Nota sobre el merge: hl.config fusiona tablas parciales (precedente:
# config/gaps.lua sobreescribe gaps_in/gaps_out/border_size sin perder el
# resto de `general` de settings.lua). Por eso user-input.lua NO incluye
# kb_layout/kb_options/follow_mouse: se quedan en settings.lua.
# ═══════════════════════════════════════════════════════════════════════════

set -u

CONF_DIR="${HYPR_CONFIG_DIR:-$HOME/.config/hypr/config}"
MODE="${1:-}"

mkdir -p "$CONF_DIR" || exit 1

# round1 <base> <mult> → "3.6" / "6" / "60" (1 decimal, sin .0 sobrante).
round1() {
    awk -v b="$1" -v m="$2" 'BEGIN {
        v = b * m * 10;
        n = int(v + (v < 0 ? -0.5 : 0.5));
        if (n % 10 == 0) printf "%d", n / 10;
        else printf "%.1f", n / 10;
    }'
}

# lua_bool <0|1> → true/false
lua_bool() { if [[ "$1" == "1" ]]; then printf "true"; else printf "false"; fi; }

# Escritura atómica: stdin → fichero destino.
write_atomic() {
    local dest="$1" tmp
    tmp="$(mktemp "$CONF_DIR/.persist-hypr.XXXXXX")" || return 1
    cat > "$tmp" || { rm -f "$tmp"; return 1; }
    mv -f "$tmp" "$dest" || { rm -f "$tmp"; return 1; }
}

# luac -p de validación: si no compila, se borra y se sale con error.
validate_or_drop() {
    local file="$1"
    if ! luac -p "$file" >/dev/null 2>&1; then
        echo "persist-hypr: luac -p falló, se descarta $file" >&2
        rm -f "$file"
        exit 1
    fi
}

reload_hypr() {
    if [[ "${HYPR_NO_RELOAD:-0}" != "1" ]]; then
        hyprctl reload >/dev/null 2>&1 || true
        if command -v notify-send >/dev/null 2>&1; then
            notify-send -t 1500 "Hyprland" "Overrides del panel aplicados (reload)" >/dev/null 2>&1 || true
        fi
    fi
}

case "$MODE" in
    animations)
        ENABLED="${2:-1}"
        SPEED="${3:-1.0}"
        [[ "$ENABLED" == "1" ]] || ENABLED=0
        [[ "$SPEED" =~ ^[0-9]+([.][0-9]+)?$ ]] || SPEED=1.0
        OUT="$CONF_DIR/user-animations.lua"
        {
            echo "-- Auto-generated by the Settings panel. Do not edit manually."
            echo "hl.config({ animations = { enabled = $(lua_bool "$ENABLED") } })"
            echo ""
            echo "-- Las 6 curvas viven en animations.lua (NO se redefinen aquí):"
            echo "-- solo se re-declaran las 12 animaciones con la velocidad"
            echo "-- escalada (speed = base * multiplier). enabled=true por"
            echo "-- animación aunque el toggle global esté off: al reactivarlo"
            echo "-- todas vuelven con sus ajustes."
            printf 'hl.animation({ leaf = "windowsIn",  enabled = true, speed = %s, bezier = "overshot", style = "popin 80%%" })\n' "$(round1 6 "$SPEED")"
            printf 'hl.animation({ leaf = "windowsOut", enabled = true, speed = %s, bezier = "easeOutExpo", style = "popin 80%%" })\n' "$(round1 5 "$SPEED")"
            printf 'hl.animation({ leaf = "windowsMove", enabled = true, speed = %s, bezier = "overshot" })\n' "$(round1 5 "$SPEED")"
            echo ""
            printf 'hl.animation({ leaf = "fadeIn",     enabled = true, speed = %s, bezier = "easeOutExpo" })\n' "$(round1 4 "$SPEED")"
            printf 'hl.animation({ leaf = "fadeOut",    enabled = true, speed = %s, bezier = "easeOutExpo" })\n' "$(round1 4 "$SPEED")"
            printf 'hl.animation({ leaf = "fadeSwitch", enabled = true, speed = %s, bezier = "easeOutExpo" })\n' "$(round1 4 "$SPEED")"
            printf 'hl.animation({ leaf = "fadeShadow", enabled = true, speed = %s, bezier = "easeOutExpo" })\n' "$(round1 4 "$SPEED")"
            printf 'hl.animation({ leaf = "fadeDim",    enabled = true, speed = %s, bezier = "easeOutExpo" })\n' "$(round1 4 "$SPEED")"
            echo ""
            printf 'hl.animation({ leaf = "border", enabled = true, speed = %s, bezier = "smooth" })\n' "$(round1 10 "$SPEED")"
            printf 'hl.animation({ leaf = "borderangle", enabled = true, speed = %s, bezier = "linear", style = "loop" })\n' "$(round1 100 "$SPEED")"
            echo ""
            printf 'hl.animation({ leaf = "workspaces", enabled = true, speed = %s, bezier = "overshot", style = "slide" })\n' "$(round1 6 "$SPEED")"
            printf 'hl.animation({ leaf = "specialWorkspace", enabled = true, speed = %s, bezier = "overshot", style = "slidevert" })\n' "$(round1 6 "$SPEED")"
        } | write_atomic "$OUT" || exit 1
        validate_or_drop "$OUT"
        echo "user-animations.lua saved (enabled=$ENABLED speed=$SPEED)"
        reload_hypr
        ;;
    input)
        SENS="${2:-0}"
        PROFILE="${3:-flat}"
        TAP="${4:-1}"
        NATURAL="${5:-1}"
        DWT="${6:-1}"
        [[ "$SENS" =~ ^-?[0-9]+([.][0-9]+)?$ ]] || SENS=0
        case "$PROFILE" in flat|adaptive) ;; *) PROFILE=flat ;; esac
        OUT="$CONF_DIR/user-input.lua"
        {
            echo "-- Auto-generated by the Settings panel. Do not edit manually."
            echo "-- Solo pointer/touchpad: kb_layout/kb_options/follow_mouse viven en"
            echo "-- settings.lua y el merge parcial de hl.config los conserva."
            echo "hl.config({ input = {"
            echo "    sensitivity   = $SENS,"
            echo "    accel_profile = \"$PROFILE\","
            echo "    touchpad = {"
            echo "        natural_scroll       = $(lua_bool "$NATURAL"),"
            echo "        disable_while_typing = $(lua_bool "$DWT"),"
            echo "        tap_to_click         = $(lua_bool "$TAP"),"
            echo "    },"
            echo "} })"
        } | write_atomic "$OUT" || exit 1
        validate_or_drop "$OUT"
        echo "user-input.lua saved (sens=$SENS profile=$PROFILE tap=$TAP natural=$NATURAL dwt=$DWT)"
        reload_hypr
        ;;
    *)
        echo "uso: persist-hypr.sh animations <0|1> <speed> | persist-hypr.sh input <sensitivity> <profile> <tap> <natural> <dwt>" >&2
        exit 2
        ;;
esac
